### ISSUE TITLE
Error on dbcompat script

### ISSUE THREAD

**Issue by BuckWoody** [microsoft/bobsql#27]
This script: https://github.com/microsoft/bobsql/blob/master/demos/sqlserver2022/IQP/cefeedback/dbcompat160.sql 

Gives this error: 

Msg 911, Level 16, State 1, Line 24
Database 'AdventureWorksDW2016_EXT' does not exist. Make sure that the name is entered correctly.

Completion time: 2022-06-20T15:06:50.9740615-04:00

**Comment by rgward** [comment]
Fixed and cleanup script
