### ISSUE TITLE
ostress not found

### ISSUE THREAD

**Issue by BuckWoody** [microsoft/bobsql#29]
On this page https://github.com/microsoft/bobsql/tree/master/demos/sqlserver2022/IQP/dopfeedback Step 11 should probably say from CMD or PowerShell. In either case, it's not working for me - I did install the pre-reqs as requested.

**Comment by rgward** [comment]
I changed the script from

.\ostress.exe

to

ostress.exe

so if the path is set right (which is now in the prereqs) it will just be picked up

**Comment by BuckWoody** [comment]
OK - I'll need to re-run the pre-reqs. Stand by.

**Comment by BuckWoody** [comment]
I included full path and it worked, it also works in CMD but failed when I used PoSH for some reason.

**Comment by BuckWoody** [comment]
That's got it. Thanks!
