### ISSUE TITLE
Consistency for indicating scripts

### ISSUE THREAD

**Issue by BuckWoody** [microsoft/bobsql#30]
On this page: 
https://github.com/microsoft/bobsql/tree/master/demos/sqlserver2022/IQP/psp

The script names are bolded, but not always. Not sure if you want to make them consistently indicated.

**Comment by rgward** [comment]
Made several changes for this and also make sure ostress.exe uses the path not local. You may need to re-run the demo

**Comment by BuckWoody** [comment]
Just completed - better now.
Comment stands for the bolding though, not sure if we want to just catch all that when I re-style the course. Any thoughts of making these Notebooks? Could be a little more useful imho.

**Comment by rgward** [comment]
All script names should be bolded. Some of the labs will go to notebooks others won't because Query Store reports only in SSMS. No need to re-style course. I'm just going to use the SQL 2019 template unless you have changed it
