### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by BuckWoody** [microsoft/bobsql#33]
On this page: 
https://github.com/microsoft/bobsql/tree/master/demos/sqlserver2022/containedag

Not sure if you meant "not" or "now" in this section: 

Demo Steps
The following are steps to create a contained AG, create a database to be part of the AG, create a SQLAgent Job, and observe the agent job is replicated to the secondary. Then you will execute a manual failover to see how the agent job is **not** available as part of the new primary.

**Comment by rgward** [comment]
thanks for the catch Fixed
