### ISSUE TITLE
Missing create database?

### ISSUE THREAD

**Issue by BuckWoody** [microsoft/bobsql#39]
On this page:
https://github.com/microsoft/bobsql/tree/master/demos/sqlserver2022/sqlledger 

It starts with adding users, but I think the createdb.sql should come first?

**Comment by rgward** [comment]
Fixed please re-check

**Comment by BuckWoody** [comment]
Now I'm getting a denied login, and on checking, the Instance is in Windows Auth. I changed it to mixed, and then it worked. Not sure if I missed a step in the setup but that might be interesting to check out.

**Comment by rgward** [comment]
Bolded prereq to ensure mixed mode auth is enabled
