### ISSUE TITLE
typo on all example folder names

### ISSUE THREAD

**Issue by sammesel** [microsoft/bobsql#5]
all folders containing code example have typo on their descriptions. for instance
Folder: ch2_intelligent_performance 
Description: exmaples for 2019 book

Description should be: **Examples for 2019 book**

**Comment by rgward** [comment]
Sam, those "descriptions" are a "commit title" that I used when I pushed these to github. They are not a description. However, I pushed an update so that this description is better read so it doesn't distract anyone
