### ISSUE TITLE
Defect restore command

### ISSUE THREAD

**Issue by Roadrunner67** [microsoft/bobsql#7]
Hi Bob, great series.
I believe there is an incomplete file here: https://github.com/microsoft/bobsql/blob/master/demos/containers/sqlcontainers/step3_docker_restorewwi.sh
The WideWorldImporters-Full.bak downloaded with pullwwi.sh contains references to Drive D: and E: and is obviously taken from a windows server. How is that restored to a linux box?

Edit: I found the solution here: https://docs.microsoft.com/en-us/sql/linux/tutorial-restore-backup-in-sql-server-container?view=sql-server-ver15, but the file still needs mending.

**Comment by rgward** [comment]
I'll take a look. thank you.

**Comment by rgward** [comment]
fixed
